(function () {
  const css = '.auth-box{position:fixed;right:18px;top:78px;z-index:9;background:#fff;border:1px solid #e5e9f1;border-radius:8px;padding:14px;box-shadow:0 8px 30px #15213b22;width:280px}.auth-box input,.auth-box select{width:100%;padding:8px;margin:4px 0;border:1px solid #d9deea;border-radius:5px}.auth-box button{background:#2457e6;color:#fff;border:0;border-radius:5px;padding:8px 12px;margin-top:6px;cursor:pointer}.auth-msg{font-size:12px;color:#667085;margin:6px 0}.auth-hide{display:none}';
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  const box=document.createElement('section');box.className='auth-box';box.innerHTML='<strong>学习账户</strong><div class="auth-msg" id="auth-msg">未登录</div><div id="auth-login"><input id="auth-user" placeholder="用户名"><input id="auth-pass" type="password" placeholder="密码（至少8位）"><input id="auth-name" placeholder="显示名称（注册时填写）"><select id="auth-role"><option value="student">学生</option><option value="parent">家长</option></select><button id="auth-submit">登录</button> <button id="auth-register">注册</button></div><div id="auth-progress" class="auth-hide"><a href="/learn.html" style="display:block;margin:6px 0;color:#2457e6;font-size:13px">进入学习工作台 →</a><select id="progress-feature"></select><input id="progress-value" type="number" min="0" max="100" value="100"><button id="progress-save">保存学习进度</button><button id="auth-logout">退出</button></div>';document.body.appendChild(box);
  let token=localStorage.getItem('aienglish_token'), user=JSON.parse(localStorage.getItem('aienglish_user')||'null');
  const msg=document.getElementById('auth-msg'), login=document.getElementById('auth-login'), progress=document.getElementById('auth-progress');
  function render(){if(token&&user){login.classList.add('auth-hide');progress.classList.remove('auth-hide');msg.textContent=user.display_name+'（'+user.role+'）';loadFeatures()}else{login.classList.remove('auth-hide');progress.classList.add('auth-hide');msg.textContent='未登录'}}
  async function loadFeatures(){const r=await fetch('/api/features');const d=await r.json();document.getElementById('progress-feature').innerHTML=d.items.map(x=>`<option value="${x.id}">${x.id}. ${x.title}</option>`).join('')}
  function onLearnPage(){return /learn\.html$/i.test(location.pathname)||location.pathname.endsWith('/learn')}
  document.getElementById('auth-submit').onclick=async()=>{try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:document.getElementById('auth-user').value,password:document.getElementById('auth-pass').value})});const d=await r.json();if(!r.ok)throw Error(d.detail||'登录失败');token=d.access_token;user=d.user;localStorage.setItem('aienglish_token',token);localStorage.setItem('aienglish_user',JSON.stringify(user));if(onLearnPage()){location.reload();return}render()}catch(e){msg.textContent=e.message}};
  document.getElementById('auth-register').onclick=async()=>{try{const payload={username:document.getElementById('auth-user').value,password:document.getElementById('auth-pass').value,display_name:document.getElementById('auth-name').value,role:document.getElementById('auth-role').value};const r=await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.detail||'注册失败');msg.textContent='注册成功，请登录'}catch(e){msg.textContent=e.message}};
  document.getElementById('progress-save').onclick=async()=>{const id=document.getElementById('progress-feature').value;const value=Number(document.getElementById('progress-value').value);const r=await fetch(`/api/users/${user.id}/progress/${id}`,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({progress:value})});msg.textContent=r.ok?'进度已保存':'保存失败：'+(await r.text())};
  document.getElementById('auth-logout').onclick=()=>{token=null;user=null;localStorage.removeItem('aienglish_token');localStorage.removeItem('aienglish_user');if(onLearnPage()){location.reload();return}render()};render();
})();
